# categorize_traces.ps1
# Replaces SSZ_TRACE("FuncName") with SSZ_TRACE_CAT(CATEGORY, "FuncName")
# in bridge.cpp based on function name prefixes.

param([string]$Path = "main/ssz/bridge.cpp")

$content = Get-Content -Path $Path -Raw

# Category mapping: function name pattern -> category
$categories = @(
    # FILE (1)
    @('"Open"',      'TRACE_FILE'),
    @('"FileClose"', 'TRACE_FILE'),
    @('"Read"',      'TRACE_FILE'),
    @('"ReadAry"',   'TRACE_FILE'),
    @('"Write"',     'TRACE_FILE'),
    @('"WriteAry"',  'TRACE_FILE'),
    @('"Seek"',      'TRACE_FILE'),
    @('"LoadAsciiText"',  'TRACE_FILE'),
    @('"SaveAsciiText"',  'TRACE_FILE'),
    @('"Delete"',    'TRACE_FILE'),
    @('"Move"',      'TRACE_FILE'),
    @('"Copy"',      'TRACE_FILE'),
    @('"Find"',      'TRACE_FILE'),
    @('"FindDir"',   'TRACE_FILE'),
    @('"CreateDir"', 'TRACE_FILE'),
    @('"RemoveDir"', 'TRACE_FILE'),
    @('"SetCurrentDir"', 'TRACE_FILE'),
    @('"GetCurrentDir"', 'TRACE_FILE'),

    # NET (2)
    @('"SocketClose"',       'TRACE_NET'),
    @('"SocketConnect"',     'TRACE_NET'),
    @('"SocketListen"',      'TRACE_NET'),
    @('"SocketAccept"',      'TRACE_NET'),
    @('"SocketSend"',        'TRACE_NET'),
    @('"SocketSendAry"',     'TRACE_NET'),
    @('"SocketRecv"',        'TRACE_NET'),
    @('"SocketRecvAry"',     'TRACE_NET'),

    # LUA (4)
    @('"LuaInit"',    'TRACE_LUA'),
    @('"NewState"',   'TRACE_LUA'),
    @('"Close"',      'TRACE_LUA'),
    @('"RunFile"',    'TRACE_LUA'),
    @('"RunString"',  'TRACE_LUA'),
    @('"GetTop"',     'TRACE_LUA'),
    @('"GetGlobal"',  'TRACE_LUA'),
    @('"Register"',   'TRACE_LUA'),
    @('"Pcall"',      'TRACE_LUA'),
    @('"Pop"',        'TRACE_LUA'),
    @('"PushNumber"', 'TRACE_LUA'),
    @('"IsNumber"',   'TRACE_LUA'),
    @('"ToNumber"',   'TRACE_LUA'),
    @('"PushBoolean"','TRACE_LUA'),
    @('"IsBoolean"',  'TRACE_LUA'),
    @('"ToBoolean"',  'TRACE_LUA'),
    @('"PushString"', 'TRACE_LUA'),
    @('"IsString"',   'TRACE_LUA'),
    @('"ToString"',   'TRACE_LUA'),
    @('"PushRef"',    'TRACE_LUA'),
    @('"ToRef"',      'TRACE_LUA'),

    # OGG (8)
    @('"NewOggVorbis"',         'TRACE_OGG'),
    @('"DeleteOggVorbis"',      'TRACE_OGG'),
    @('"OggVorbisOpen"',        'TRACE_OGG'),
    @('"OggVorbisClear"',       'TRACE_OGG'),
    @('"OggVorbisPcmTotal"',    'TRACE_OGG'),
    @('"OggVorbisChannels"',    'TRACE_OGG'),
    @('"OggVorbisRate"',        'TRACE_OGG'),
    @('"OggVorbisRead"',        'TRACE_OGG'),
    @('"OggVorbisSeek"',        'TRACE_OGG'),

    # UTIL (16)
    @('"YesNo"',           'TRACE_UTIL'),
    @('"VeryUnsafeCopy"',  'TRACE_UTIL'),
    @('"GetClipboardStr"', 'TRACE_UTIL'),
    @('"TazyuuCheck"',     'TRACE_UTIL'),
    @('"CloseTazyuuHandle"','TRACE_UTIL'),
    @('"GetInifileString"','TRACE_UTIL'),
    @('"GetInifileInt"',   'TRACE_UTIL'),
    @('"WriteInifileString"','TRACE_UTIL'),
    @('"UnCompress"',      'TRACE_UTIL'),
    @('"UbytesToStr"',     'TRACE_UTIL'),
    @('"StrToUbytes"',     'TRACE_UTIL'),
    @('"AsciiToLocal"',    'TRACE_UTIL'),
    @('"SetSharedString"', 'TRACE_UTIL'),
    @('"GetSharedString"', 'TRACE_UTIL'),
    @('"InputStr"',        'TRACE_UTIL'),
    @('"NewClient"',       'TRACE_UTIL'),
    @('"DeleteClient"',    'TRACE_UTIL'),
    @('"ClientStart"',     'TRACE_UTIL'),
    @('"ClientStop"',      'TRACE_UTIL'),
    @('"ClientBufferReady"','TRACE_UTIL'),
    @('"ClientSetBuffer"', 'TRACE_UTIL'),
    @('"NewRegex"',        'TRACE_UTIL'),
    @('"DeleteRegex"',     'TRACE_UTIL'),
    @('"RegexSearch"',     'TRACE_UTIL'),
    @('"ShellOpen"',       'TRACE_UTIL'),
    @('"MoveTrash"',       'TRACE_UTIL'),
    @('"ThreadDelay"',     'TRACE_UTIL'),
    @('"Alert"',           'TRACE_UTIL'),

    # MATH (32)
    @('"Sin"',    'TRACE_MATH'),
    @('"Cos"',    'TRACE_MATH'),
    @('"Tan"',    'TRACE_MATH'),
    @('"ASin"',   'TRACE_MATH'),
    @('"ACos"',   'TRACE_MATH'),
    @('"ATan"',   'TRACE_MATH'),
    @('"Log"',    'TRACE_MATH'),
    @('"Ln"',     'TRACE_MATH'),
    @('"Exp"',    'TRACE_MATH'),
    @('"Sqrt"',   'TRACE_MATH'),
    @('"Ceil"',   'TRACE_MATH'),
    @('"Floor"',  'TRACE_MATH'),
    @('"IsFinite"','TRACE_MATH'),
    @('"IsInf"',  'TRACE_MATH'),
    @('"IsNaN"',  'TRACE_MATH'),
    @('"TickCount"','TRACE_MATH'),
    @('"UnixTime"','TRACE_MATH'),

    # SDL (64)
    @('"DrawTTF"',           'TRACE_SDL'),
    @('"Init"',              'TRACE_SDL'),
    @('"GlInit"',            'TRACE_SDL'),
    @('"RendererInit"',      'TRACE_SDL'),
    @('"GetRendererInfo"',   'TRACE_SDL'),
    @('"EnablePerfMonitor"', 'TRACE_SDL'),
    @('"End"',               'TRACE_SDL'),
    @('"FullScreenExclusive"','TRACE_SDL'),
    @('"FullScreen"',        'TRACE_SDL'),
    @('"WindowType"',        'TRACE_SDL'),
    @('"GetWidth"',          'TRACE_SDL'),
    @('"GetHeight"',         'TRACE_SDL'),
    @('"WindowSize"',        'TRACE_SDL'),
    @('"AspectRatio"',       'TRACE_SDL'),
    @('"SetOpacity"',        'TRACE_SDL'),
    @('"TakeScreenShot"',    'TRACE_SDL'),
    @('"UpdateGLViewport"',  'TRACE_SDL'),
    @('"PlayVideo"',         'TRACE_SDL'),
    @('"PollEvent"',         'TRACE_SDL'),
    @('"GetLastChar"',       'TRACE_SDL'),
    @('"KeyState"',          'TRACE_SDL'),
    @('"JoystickButtonState"','TRACE_SDL'),
    @('"PollInputBitmask"',  'TRACE_SDL'),
    @('"SoftFill"',          'TRACE_SDL'),
    @('"Fill"',              'TRACE_SDL'),
    @('"IMGLoad"',           'TRACE_SDL'),
    @('"DecodePNG8"',        'TRACE_SDL'),
    @('"BlitSurface"',       'TRACE_SDL'),
    @('"CreatePaletteSurface"','TRACE_SDL'),
    @('"SetColorKey"',       'TRACE_SDL'),
    @('"Flip"',              'TRACE_SDL'),
    @('"AllocSurface"',      'TRACE_SDL'),
    @('"FreeSurface"',       'TRACE_SDL'),
    @('"Delay"',             'TRACE_SDL'),
    @('"GetTicks"',          'TRACE_SDL'),
    @('"CursorShow"',        'TRACE_SDL'),
    @('"OpenFont"',          'TRACE_SDL'),
    @('"CloseFont"',         'TRACE_SDL'),
    @('"RenderFont"',        'TRACE_SDL'),
    @('"SetSndBuf"',         'TRACE_SDL'),
    @('"PlayBGM"',           'TRACE_SDL'),
    @('"PauseBGM"',          'TRACE_SDL'),
    @('"SendOpenBGM"',       'TRACE_SDL'),
    @('"SendCloseBGM"',      'TRACE_SDL'),
    @('"SendWriteBGM"',      'TRACE_SDL'),
    @('"SetVolume"',         'TRACE_SDL'),
    @('"FadeInBGM"',         'TRACE_SDL'),
    @('"FadeOutBGM"',        'TRACE_SDL'),
    @('"RenderMugenZoom"',   'TRACE_SDL'),
    @('"RenderFontBatch"',   'TRACE_SDL'),
    @('"RenderMugenShadow"', 'TRACE_SDL'),
    @('"Load8bitTexture"',   'TRACE_SDL'),
    @('"LoadPngTexture"',    'TRACE_SDL'),
    @('"DeleteGlTexture"',   'TRACE_SDL'),
    @('"GlSwapBuffers"',     'TRACE_SDL'),
    @('"InitMugenGl"',       'TRACE_SDL'),
    @('"RenderMugenGl"',     'TRACE_SDL'),
    @('"RenderMugenGlFc"',   'TRACE_SDL'),
    @('"RenderMugenGlFcS"',  'TRACE_SDL'),
    @('"MugenFillGl"',       'TRACE_SDL'),
    @('"BindGlContext"',     'TRACE_SDL'),
    @('"UnbindGlContext"',   'TRACE_SDL'),

    # SYS (128)
    @('"ActionInit"',              'TRACE_SYS'),
    @('"BgInit"',                  'TRACE_SYS'),
    @('"BgSplitParams"',           'TRACE_SYS'),
    @('"DebugLoadFile"',           'TRACE_SYS'),
    @('"DebugRunFile"',            'TRACE_SYS'),
    @('"FontInit"',                'TRACE_SYS'),
    @('"FontRenderText"',          'TRACE_SYS'),
    @('"CharInit"',                'TRACE_SYS'),
    @('"CommandInit"',             'TRACE_SYS'),
    @('"FightInit"',               'TRACE_SYS'),
    @('"FightingInit"',            'TRACE_SYS'),
    @('"SystemScriptInit"',        'TRACE_SYS'),
    @('"TriggerScriptRegisterFunction"','TRACE_SYS'),
    @('"StageInit"',               'TRACE_SYS'),
    @('"StageLoad"',               'TRACE_SYS'),
    @('"StageAction"',             'TRACE_SYS'),
    @('"StageBgDraw"',             'TRACE_SYS'),
    @('"StageClear"',              'TRACE_SYS'),
    @('"StageReset"',              'TRACE_SYS'),
    @('"ScriptInit"',              'TRACE_SYS'),
    @('"StateBuilderInit"',        'TRACE_SYS'),
    @('"SystemAddChar"',           'TRACE_SYS'),
    @('"SystemAddStage"',          'TRACE_SYS'),
    @('"SystemGetStageName"',      'TRACE_SYS'),
    @('"SystemSetStageNo"',        'TRACE_SYS'),
    @('"SystemSelectStage"',       'TRACE_SYS'),
    @('"SystemAddSelchr"',         'TRACE_SYS'),
    @('"SystemSelReset"',          'TRACE_SYS'),
    @('"LoaderError"',             'TRACE_SYS'),
    @('"LoaderStage"',             'TRACE_SYS'),
    @('"LoaderChara"',             'TRACE_SYS'),
    @('"LoaderStateCompile"',      'TRACE_SYS'),
    @('"LoaderLoad"',              'TRACE_SYS'),
    @('"LoaderReset"',             'TRACE_SYS'),
    @('"LoaderRunTread"',          'TRACE_SYS'),
    @('"CommonFlagInit"',          'TRACE_SYS'),
    @('"CommonResetRemapInput"',   'TRACE_SYS'),
    @('"CommonSetSize"',           'TRACE_SYS'),
    @('"CommonTickFrame"',         'TRACE_SYS'),
    @('"CommonTickNextFrame"',     'TRACE_SYS'),
    @('"CommonTickInterpola"',     'TRACE_SYS'),
    @('"CommonAddFrameTime"',      'TRACE_SYS'),
    @('"CommonResetFrameTime"',    'TRACE_SYS'),
    @('"CommonMatchOver"',         'TRACE_SYS'),
    @('"CommonAtoi"',              'TRACE_SYS'),
    @('"CommonAtof"',              'TRACE_SYS'),
    @('"CommonLoadText"',          'TRACE_SYS'),
    @('"SffInit"',                 'TRACE_SYS'),
    @('"SffLoadFile"',             'TRACE_SYS'),
    @('"SffGetSprite"',            'TRACE_SYS'),
    @('"ShareCopy"',               'TRACE_SYS'),
    @('"SharePush"',               'TRACE_SYS'),
    @('"SoundResourceInit"',       'TRACE_SYS'),
    @('"SoundSndbufClear"',        'TRACE_SYS'),
    @('"SoundMixSounds"',          'TRACE_SYS'),
    @('"SoundPlaySound"',          'TRACE_SYS'),
    @('"SoundStopSound"',          'TRACE_SYS'),
    @('"VideoPlay"',               'TRACE_SYS'),
    @('"SdleventEventUpdate"',     'TRACE_SYS'),
    @('"SdleventEvent"',           'TRACE_SYS')
)

$total = 0
foreach ($entry in $categories) {
    $funcName = $entry[0]
    $category = $entry[1]
    $oldStr = "SSZ_TRACE($funcName)"
    $newStr = "SSZ_TRACE_CAT($category, $funcName)"
    if ($content -match [regex]::Escape($oldStr)) {
        $content = $content -replace [regex]::Escape($oldStr), $newStr
        $total++
    }
}

Set-Content -Path $Path -Value $content -NoNewline
Write-Host "Replaced $total SSZ_TRACE calls with categorized versions."
